{
 "title": "1-Router Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Basic Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Load",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "router_ooxxcc_com.load.*.*" }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "router_ooxxcc_com.memory.*" }
   ]
  },
  { "title": "Interface", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Rx Bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "target": "aliasSub(router_ooxxcc_com.interface-*.if_octets.rx, '.*interface-(.*).if.*', '\\1')"
    }
   ]
  },
  {
   "title": "Tx Bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "target": "aliasSub(router_ooxxcc_com.interface-*.if_octets.tx, '.*interface-(.*).if.*', '\\1')"
    }
   ]
  },
  { "title": "Traffic Accounting", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "download",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "target": "aliasSub(cumulative(sortByTotal(router_ooxxcc_com.accounting-ACCOUNTING_OUTPUT_CHAIN.*)), '.*traffic-(.*),.*', '\\1')"
    }
   ]
  },
  {
   "title": "upload",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "target": "aliasSub(cumulative(sortByTotal(router_ooxxcc_com.accounting-ACCOUNTING_INPUT_CHAIN.*)), '.*traffic-(.*),.*', '\\1')"
    }
   ]
  }
 ]
}